version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: ./dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: ./dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookshelf_db
      MYSQL_USER: bookshelf_db
      MYSQL_PASSWORD: bookshelf_pass
